### DISCUSSION TITLE
Taking an action when an announcement fails for any reason

### DISCUSSION THREAD

**Discussion by dimatx** [nimroddolev/chime_tts#165] [Q&A]
Hey @nimroddolev.

Thanks again for your work, the announcements have been reliable on the Sonos since the recent fixes.

I'm curious if there's a way to take an action at the end of my automation/script that will send me a notification through other means if and only if the announcement fails for any reason (E.g., a timeout, error reaching TTS server, unknown error, etc)

Scenario: Just recently my announcements started failing because I had unplugged one of my speakers and the join was failing to form (seems like if any of the speakers are unavailable, the group is not formed with the rest). In this case, I'd like to send a push notification to the app, or to my uptime service (webhook) that indicates an outage. Is there a way to capture that failure with a trigger or a condition?

Dima

**Comment by d-allin** [comment]
I'm just passing through, but you can probably set up something to trigger from the event platform.
This is an example, but you can adopt this to be a lot more generic.

```yaml
- alias: "Chime TTS Integration error"
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
      logger: custom_components.chime_tts.helpers.media_player_helper
  condition:
    condition: template
    value_template: '{{ "Failed to resume playback on media_player.office_speaker" in trigger.event.data.message[0] }}'
  action:
  - service: notify.notification_service_name
    data:
        message: Playback failed to resume.
```

Note that events for system_log_event must be explicitly enabled in `configuration.yaml` via the `fire_event` parameter.

```yaml
system_log:
  # required when used for triggers
  fire_event: true
```

Documentation for the [System Log](https://www.home-assistant.io/integrations/system_log) has more details, but that should get you started.
