### DISCUSSION TITLE
Application Question

### DISCUSSION THREAD

**Discussion by Jeff613333** [nimroddolev/chime_tts#166] [Q&A]
I am considering using Chime with multiple binary sensors, approximately 20, and a BolaButty portable Bluetooth speaker.

The plan is to have the location of the sensor that changes state announced. For example, I have sensors monitoring for leaks in the bathroom, kitchen, and laundry room.  If any of these sense a leak I would like the location announced.

I have two questions.  First, is Chime appropriate for this use or am I misunderstanding its application?  Second, is a Bluetooth speaker an appropriate announcing device or should I be considering something else?

**Comment by nimroddolev** [comment]
Hi @Jeff613333,

Yes, the use case you suggested sounds appropriate to me. You can use Chime TTS with any of your `media_player` entities. For the example you included, you could create an automation similar to the following:
```
automation:
  - alias: "Announce Water Leak"
    trigger:
      - platform: state
        entity_id: binary_sensor.leak_detector
        to: "on"
    action:
      - service: chime_tts.say
        data:
          entity_id: media_player.living_room_speaker
          chime_path: dun_dun_dun
          message: >
            {% set entity_id = 'binary_sensor.leak_detector' %}
            {% set device_id = states[entity_id].attributes.device_id %}
            {% set area_id = device_entities(device_id) | map(attribute='area_id') | first %}
            {% set room = area_id | area_name if area_id else 'an unknown location' %}
            There's a leak in the {{ room }}
```
