### DISCUSSION TITLE
Is there a maximum offset you can do?

### DISCUSSION THREAD

**Discussion by SCBionicle** [nimroddolev/chime_tts#197] [Q&A]
I'm trying to do a breaking news alert sound with a starting stinger track and then background music while TTS is announcing the breaking news. But it seems to be going to a long sequence rather than offlaping.

Here's a sample:
```yaml
action: chime_tts.say
target:
  entity_id: media_player.player
data:
  message: 
    - chime: /media/share_volume/SFX/breaking-news-opening.mp3 #(length: 6 seconds)
    - chime: /media/share_volume/SFX/breaking-news-background.mp3 #(length: 1 minute 22 seconds)
      offset: -1500
    - tts: This is a test of unreal proportions.
      offset: -40000
    - tts: this is the 2nd phrase
    - tts: this is a the final phrase
  announce: false
```

Perhaps, I'm doing something wrong. Any tips anyone has or is this a bug?
