### DISCUSSION TITLE
How To Use Variables For Message in Chime_TTS

### DISCUSSION THREAD

**Discussion by ColtonYYZ** [nimroddolev/chime_tts#268] [General]
Hey @nimroddolev! I wanted to know if there's a way to use a variable set during an automation, in the message area of Chime TTS? I tried but I get the following error:

Error running action
Error rendering data template: UndefinedError: 'response' is undefined

Below is my YAML. The 'action: tts.speak' section is just for my records, but that part works when enabled. The part just before it 'action: chime_tts.say' does not work; giving me the error above.
```
alias: Welcome Home Colton!
description: ""
triggers:
  - trigger: state
    entity_id:
      - person.colton
    to: home
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - action: google_generative_ai_conversation.generate_content
    metadata: {}
    data:
      prompt: Welcome Colton home with a short sarcastic joke!
    response_variable: response
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.35
    target:
      device_id: bec8cf8ad0fcf70965e8eb5cce0f4654
  - action: chime_tts.say
    metadata: {}
    data:
      message: "{{ response.text }}"
      tts_platform: amazon_polly
      tts_speed: 121
      join_players: true
      announce: true
    target:
      device_id: 64d3379db7af94d2263ffdafde74ee35
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.colton_s_echo_show
      message: "{{ response.text }}"
    target:
      entity_id: tts.google_en_com_au
    enabled: false
mode: single
```
