### DISCUSSION TITLE
How to check if message is defined or not

### DISCUSSION THREAD

**Discussion by BigFan00777** [nimroddolev/chime_tts#56] [Q&A]
Hi all
I'm battling to detect if message is defined or not. If it is not defined I get an error in the error log, but the media file is still playing. I have a script that processes my messages and some triggers evaluate to message being an empty string or undefined. I have tried many option. Any assistance would be appreciated. Thank you in advance

```
broadcast_my_message:
  alias: Broadcast My Message
  sequence:
    - if: "{{ message != empty }}"
      then:
        - service: chime_tts.say
          data:
            chime_path: chord
            message: >
              {{ message | default("hello") }}
            volume_level: 0.5
            tts_platform: google_translate
          target:
            entity_id:
              - media_player.home_group
```
