### DISCUSSION TITLE
v0.10.2-beta2

### DISCUSSION THREAD

**Discussion by nimroddolev** [nimroddolev/chime_tts#62] [Announcements]
## ✨ Features
* The `chime_tts.say` and `chime_tts.say_url` services have a new `Audio Conversion` parameter to convert audio to work with <ins>Alexa speakers</ins>. It can also be utilized to specify an arbitrary list of arguments for an <ins>FFmpeg</ins> conversion job.
* The duration of the generated audio (in seconds) has been added to the `chime_tts.say_url` service response (`duration`), eg:
  ```
  url: https://{YOUR_HA_ADDRESS}/local/chime_tts/x3u5vr88.mp3
  duration: 4.883
  ```

## 🧰 Improvements
* Added support for setting file type in FFmpeg conversion
* Added drop down UI to convert audio to Alexa speaker specifications, or to set custom arguments to run an FFmpeg conversion
* Increased volume of whistle chime

## 🐞 Bugfixes
* Fixed bug where `chime_tss.say` queue would become stuck until Home Assistant was rebooted
* Fix for constructing folder paths
* Potential fix for external url
* Potential fix for stuck queue

## What's Changed
* Update README.md by @nimroddolev in https://github.com/nimroddolev/chime_tts/pull/61

**Full Changelog**: https://github.com/nimroddolev/chime_tts/compare/v0.10.2-beta1...v0.10.2-beta2

**Comment by KEV-github** [comment]
Good morning and thanks for all your help.
I have updated to the latest beta. Some nice changes in there.
Unfortunately mine is still generating HTTP local address.
I bet it's something simple that's stopping it. 🤦🏻‍♂️

![Image 22-12-2023 at 08 38](https://github.com/nimroddolev/chime_tts/assets/57045329/9eddfa9b-785f-4fd0-8559-75e021beb753)

**Reply by nimroddolev** [reply]
Thank you, i'm sorry you're still having issues.

I remembered that the configuration.yaml can include [your internal and external addresses](https://www.home-assistant.io/docs/configuration/basic/).

Can you please try adding the following to your configuration.yaml, restart Home Assistant and try again?
```
homeassistant:
  external_url: "https://_____________.nabu.casa"
  internal_url: "http://192.168.1.97:8123/"
```

**Reply by KEV-github** [reply]
Yipeee. We have lift off. That worked. Now to work out the correct yaml config  to announce on Alexa.

**Reply by nimroddolev** [reply]
Excellent!

It should now just be a simple matter of using the `url` result from the `chime_tss.say_url` in the `notify.alexa_media` service:

```
sequence:
  - service: chime_tts.say_url
    data:
      chime_path: bells
      tts_platform: google_translate
      audio_conversion: "Alexa”
      message: "Hello world!"
    response_variable: chime_tts
  - service: notify.alexa_media
    data:
      message: <audio src= "{{chime_tts.url}}"/>
      target:
        - media_player.echo_speaker
      data:
        type: tts
```
