### DISCUSSION TITLE
Script to Call Chime_tts and broadcast an annoucement on Amazon Alexas using Piper

### DISCUSSION THREAD

**Discussion by dbullendsl** [nimroddolev/chime_tts#65] [Show and tell]
This script is an example of how chime_tts:say_url can be used to create an announcement over Amazon Alexas.

```
alias: call chime tts
sequence:
  - service: chime_tts.say_url
    data:
      chime_path: "{{chime_path}}"
      end_chime_path: "{{end_chime_path}}"
      delay: 450
      final_delay: 0
      tts_playback_speed: 100
      tts_platform: tts.piper
      audio_conversion: Alexa
      message: "{{message}}"
      options: "voice: {{voice}}"
    response_variable: chime_tts
  - service: notify.alexa_media
    data:
      message: <audio src= "{{chime_tts.url}}"/>
      target: "{{target}}"
      data:
        type: tts
    enabled: true
mode: single
fields:
  chime_path:
    selector:
      text: null
    name: chime_path
  end_chime_path:
    selector:
      text: null
    name: end_chime_path
  message:
    selector:
      text:
        multiple: false
        multiline: true
    name: message
  voice:
    selector:
      select:
        options:
          - en_GB-alba-medium
          - en_GB-northern_english_male-medium
          - en_GB-southern_english_female-low
          - en_GB-vctk-medium
          - en_US-amy-medium
          - en_US-hfc_male-medium
          - en_US-joe-medium
          - en_US-kusal-medium
          - en_US-lessac-medium
          - en_US-libritts_r-medium
          - en_US-ryan-medium
    name: voice
    default: en_US-lessac-medium
    required: true
  target:
    selector:
      entity:
        multiple: true
        include_entities:
          - media_player.kitchen_echo_show
          - media_player.sunroom_echo_dot
          - media_player.master_bedroom_echo_dot
          - media_player.office_echo_dot
          - media_player.media_room_echo_dot
          - media_player.utility_room_echo_flex
    name: target
    required: true
```
The values of your media_player names will have to be changed according to your personal configuration. When you create an automation that does a call service to this script you'll need to choose the values for chime_path and end_chime_path (may be left blank), fill in the message, select the voice and the target players. 

Here's an example of an announcement created using this script:

https://github.com/nimroddolev/chime_tts/assets/98482191/f8e06b1b-451e-438b-bfe0-a055a5c49367
