### ISSUE TITLE
2024.4: Gender is no longer an option for Nabu Casa Voice

### ISSUE THREAD

**Issue by Coder84619** [nimroddolev/chime_tts#104]
### System Health details

--

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

HA 2024.4 threw a warning that for the Nabu Casa voice, the "gender" option is deprecated. You now need to use the "voice" option. Please update chime to use the new "voice" option. 

### Reproduction steps

1. Install HA 2024.4
2. Call ChimeTTS with the Nabu casa voice
3. See a warning pop up
...

### Debug logs

```text
--
```

**Comment by nimroddolev** [comment]
Thanks @Coder84619.

I just released a new beta which replaces the deprecated `gender` parameter with `voice`.
I'd appreciate it if you could please install the new version and let me know if it's working for you, as well as any other feedback you might have.

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v1.0.1-beta1` from the updated version drop-down list
1. Restart Home Assistant

**Comment by Coder84619** [comment]
@nimroddolev I can confirm the beta resolves the issue. My only tip would be to add male/female drop down to the voice options. I had to google nabua casa TTS to find out the voice options.

**Comment by Coder84619** [comment]
well I manually typed "male" or "female" in the "voice" box and the voice changed to male or female.

**Comment by nimroddolev** [comment]
Strange, when I run the following I hear the standard female voice:

```
service: chime_tts.say
target:
  entity_id: media_player.kitchen
data:
  volume_level: 1
  tts_platform: cloud
  voice: male
  message: hi there
  ```

**Comment by Coder84619** [comment]
Odd, as I always get the male voice. Never knew there was a female before I typed it in the field.

**Comment by nimroddolev** [comment]
Odd indeed. Could you please share your YAML?
I can only change the voice's gender by selecting a male/female voice and not by defining the gender.

**Comment by Coder84619** [comment]
I've never heard the female voice until I played with the "Voice"/Gender option. I didn't even know she existed. 

Male voice: 

```
service: chime_tts.say
target:
  entity_id: media_player.google_speaker_office
data:
  chime_path: chord
  end_chime_path: chord
  offset: 450
  final_delay: 0
  tts_speed: 100
  tts_pitch: 0
  volume_level: 0.55
  message: Meeting in two minutes.
  tts_platform: cloud
```
