### ISSUE TITLE
Set volume for each device when calling multiple devices

### ISSUE THREAD

**Issue by input5** [nimroddolev/chime_tts#108]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'd like to use Chime to group notifications but I need my players to play at different volumes (some are in bedrooms).

### Describe the solution you'd like

It would be great if we could set the player volume per player via some sort of optional field.

### Describe alternatives you've considered

Calling Chime multiple times with different volumes, unfortunately this means some speakers will be out of sync.

### Additional context

None

**Comment by nimroddolev** [comment]
Thank you for the suggestion @input5, 👍 I will try to implement support in an upcoming release.

I think a good way to implement this would be to extend the `volume` parameter so that it also allows a dictionary value (in addition to the float value used today to apply to all media_player/s). Using a dictionary would allow users to specify the desired volume level for each individual media_player as the value:

```
service: chime_tts.say
target:
  entity_id:
    - media_player.speaker_1
    - media_player.speaker_2
    - media_player.speaker_3
data:
  tts_platform: google_translate
  message:
    - tts: Hello world
  volume:
    - media_player.speaker_1: 0.5
    - media_player.speaker_2: 0.2
    - media_player.speaker_3: 1.0
```

**Comment by input5** [comment]
That would be perfect, thanks for responding so fast. Let me know if I can help (e.g. with testing).

**Comment by input5** [comment]
How would that handle a case where the user has specified a volume for one media_player but not for another.

e.g.

"""
service: chime_tts.say
target:
  entity_id:
    - media_player.speaker_1
    - media_player.speaker_2
    - media_player.speaker_3
data:
  tts_platform: google_translate
  message:
    - tts: Hello world
  volume:
    - media_player.speaker_1: 0.5
"""

**Comment by input5** [comment]
For example with this code:

```
# Parsing volume
volume = data.get(ATTR_MEDIA_VOLUME_LEVEL)
if volume is not None:
    if isinstance(volume, float):
        # Apply the same volume to all media players
        options[ATTR_MEDIA_VOLUME_LEVEL] = {entity_id: volume for entity_id in entity_ids}
    elif isinstance(volume, dict):
        # Apply individual volumes specified in the dictionary
        for entity_id in entity_ids:
            if entity_id not in volume:
                 # Do we through an exception here or do we choose some sort of default value?
                _LOGGER.warning("No volume specified for '%s', using default.", entity_id)
                volume[entity_id] = 1.0  # Default volume level
        options[ATTR_MEDIA_VOLUME_LEVEL] = volume
    else:
        _LOGGER.error("Invalid volume type: %s. Expected float or dict.", type(volume).__name__)
```

**Comment by nimroddolev** [comment]
In cases where volume levels are specified for only some of the media_players included in the service call, those media_players which do not have a specified volume will remain at their current volume level.
I don't think it makes sense to throw an exception or use a default value.

I think that ultimately if a user decides to fine-tune the volume level per-media_player, they should make sure to include each media_player.

**Comment by nimroddolev** [comment]
I have released a beta which adds support for setting media_player-specific volume levels, v1.0.1-beta1.
I'd appreciate it if you could please install it and let me know if it's working for you, and if you have any feedback 👍

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v1.0.1-beta1` from the updated version drop-down list
1. Restart Home Assistant

**Comment by input5** [comment]
```
service: chime_tts.say
target:
  device_id:
    - <redacted device 1>
    - <redacted device 2>
data:
  chime_path: marimba
  end_chime_path: ""
  offset: 450
  final_delay: 0
  tts_speed: 100
  tts_pitch: 0
  tts_platform: tts.piper
  message: This is a test!
  options:
    volume_level:
        media_player.conservatory_sonos: 0.10
        media_player.lounge_sonos: 0.80
```

Both players seem to be playing at the same volume.

**Comment by nimroddolev** [comment]
Thank you.

Perhaps the issue might be that you used device_ids in your list of targets instead of entity_ids? I will add support for this case, but could you please try again with entity_ids just to confirm the volume levels are changed as expected?

**Comment by nimroddolev** [comment]
I was too quick with my reply.

The issue is that you placed `volume_level` under `options` when it should be on the same level as the other parameters, eg:

```
service: chime_tts.say
target:
  device_id:
    - <redacted device 1>
    - <redacted device 2>
data:
  chime_path: marimba
  end_chime_path: ""
  offset: 450
  final_delay: 0
  tts_speed: 100
  tts_pitch: 0
  tts_platform: tts.piper
  message: This is a test!
  volume_level:
    media_player.conservatory_sonos: 0.10
    media_player.lounge_sonos: 0.80
```
