### ISSUE TITLE
Piper voice support

### ISSUE THREAD

**Issue by MJHeijster** [nimroddolev/chime_tts#175]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Piper has support for many voices. One of them is en_US-hfc_female-medium. I want to be able to set in the chime_tts.say service which voice it should use.

### Describe the solution you'd like

Pass voice parameter to Piper in a way piper understands. 

### Describe alternatives you've considered

None seem to come to mind outside of using Chime TTS. 

### Additional context

I use the lscr.io/linuxserver/piper docker image outside of my Home Assistant because it is more powerful, but it has less uptime. Setting the default piper voice doesn't seem to trigger said voice when called from Chime TTS. When I trigger the voice from a voice assistant in home assistant, it works, so the voice is supported.

I might be missing something, but as far as I can tell, I can't pass the voice to piper with Chime.

**Comment by dbullendsl** [comment]
I'm running Chime_TTS using Piper voices and find that it works just fine. I can't duplicate the configuration you have for the installation of Piper - instead I have Piper installed on the HA mini intel PC that runs the HA Core. 

At the bottom of the list of parameters for Chime_TTS: Say there is a Voice parameter, check it and put in the voice name you want to use in the field.  Works just fine.

```
service: chime_tts.say
data:
  message: This is a test
  tts_platform: tts.piper
  volume_level: 0.3
  voice: en_US-hfc_female-medium
target:
  entity_id: media_player.sonos_beam
```

**Comment by MJHeijster** [comment]
Hmm odd, looks like this is an issue specific between the docker image and Chime. 

In my case tts.piper is the home assistant add-on, tts.piper2 is the one on my nas with the docker image. 

```
service: chime_tts.say
data:
  message: This is a test 
  tts_platform: tts.piper
  volume_level: 0.3 
  voice: en_US-hfc_male-medium
target:
  entity_id: media_player.living_room_echo
``` 
works

But 
```
service: chime_tts.say
data:
  message: This is a test 
  tts_platform: tts.piper2
  volume_level: 0.3 
  voice: en_US-hfc_male-medium
target:
  entity_id: media_player.living_room_echo
``` 
immediately returns when I press Call Service. Most notable log: - Error calling tts.media_source.generate_media_source_id: Invalid options found: ['voice']

**Comment by MJHeijster** [comment]
Hmm the weird thing is that I do get the voice I set in the docker container config for piper if I call tts.speak directly. 
```
service: tts.speak
data:
  message: this is a test
  media_player_entity_id: media_player.living_room_echo
target:
  entity_id: tts.piper_2

``` 

When I use Chime, it uses a default voice. Not sure what's going on there.
