### ISSUE TITLE
language selection problem google cloud or google translate nl-BE 

### ISSUE THREAD

**Issue by Tommiebelg** [nimroddolev/chime_tts#210]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1458
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 2 november 2024 om 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
instance_id | 8e308f28c1314a6a9bc161a13c8b12dc
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 13.7 GB
disk_used | 10.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), Z-Wave JS (0.8.1), File editor (5.8.0), Advanced SSH & Web Terminal (19.0.0), Mosquitto broker (6.4.1), ESPHome (2024.10.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 12
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 oktober 2024 om 22:04
-- | --
current_recorder_run | 1 november 2024 om 12:12
estimated_db_size | 388.85 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I tried setting the Google cloud TTS service language to Belgian Dutch, "Flemish" or "Vlaams" 
Tried the same for Google translate TTS service
I used the nl-BE argument as this setting works in tts.cloud_say.
I would also like to be able to select one of the 2 available Neuralnet voices; DeraNeural or ArnaudNeural

Thank you for your help and also, this is an amazing piece of programming!

### Reproduction steps

Action settings: (this one does'nt work) Should be Flemish (Language spoken in largest part op Belgium)
```
action: chime_tts.say
metadata: {}
data:
  message: Testboodschap
  announce: true
  tts_platform: google_cloud
  language: nl-BE
target:
  entity_id: media_player.keuken_hoofd

```
This works to select Dutch (Language spoken in Holland)
```
action: chime_tts.say
metadata: {}
data:
  message: Testboodschap
  announce: true
  tts_platform: google_cloud
  language: nl
target:
  entity_id: media_player.keuken_hoofd

```
as example:
This cloud_say works to select Flemish (Language spoken in largest part of Belgium) with Female Neural voice

```
action: tts.cloud_say
metadata: {}
data:
  cache: false
  entity_id: media_player.keuken_hoofd
  language: nl-BE
  message: Testboodschap
  options:
    voice: DeraNeural

```

### Debug logs

```text
2024-11-01 12:27:51.723 WARNING (MainThread) [custom_components.chime_tts] Error generating TTS audio from messsage segment #1: {'type': 'tts', 'message': 'Testboodschap'}
2024-11-01 12:27:51.724 ERROR (MainThread) [custom_components.chime_tts] async_get_playback_audio_path --> Audio has no duration
2024-11-01 12:27:51.724 ERROR (MainThread) [custom_components.chime_tts] async_get_playback_audio_path --> Unable to generate local audio file
```
