### ISSUE TITLE
Announce does not work for 2 different radiostations (2 different Sonos devices)

### ISSUE THREAD

**Issue by KrisHoobergs** [nimroddolev/chime_tts#43]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have 2 Sonos devices where each is playing another radio station.  After using chimeTSS they both plays the same radio station.  I bound the system and unbound the afterwards so both set to true.  Also announce is set to true.
This is my piece of code
```
service: chime_tts.say
data:
  chime_path: mp3_path_placeholder-whistle
  end_chime_path: mp3_path_placeholder-bright
  delay: 450
  final_delay: 0
  tts_playback_speed: 100
  volume_level: 0.25
  message: Tjoep is vertrokken bij Henrioulle
  tts_platform: google_translate
  gender: female
  join_players: true
  unjoin_players: true
  announce: true
target:
  entity_id:
    - media_player.sonoskitchen
    - media_player.sonosmove
```

### Describe the solution you'd like

I would like to have the sonos systems play the radiostation that was playing before the message was send.

### Describe alternatives you've considered

Not applicable

### Additional context

Not applicable

**Comment by nimroddolev** [comment]
Hi @KrisHoobergs,

Sorry you've been having issues. As I understand the built it join/unjoin feature in Home Assistant (the same one being used by Chime TTS) does not always play nicely with Sonos. Other Sonos users have reported that a workaround is to use the Sonos integration's snapshot/restore feature, in conjunction with Chime TTS:

```
 - service: sonos.snapshot
    data:
      with_group: true
      entity_id: all

  - service: chime_tts.say
    data:
      chime_path: custom_components/chime_tts/mp3s/bells.mp3
      message: This is a test
      tts_platform: google_cloud
      join_players: true
    enabled: true
    target:
      entity_id:
        - media_player.lounge_sonos
        - media_player.porch_sonos
        - media_player.diningroom_sonos
        - media_player.halfbath_sonos
        - media_player.kitchen_sonos
        - media_player.office_sonos
        - media_player.garage_sonos

  - service: sonos.restore
    data:
      with_group: true
      entity_id: all
```
