### ISSUE TITLE
chime_tts.say plays wrong/older messages

### ISSUE THREAD

**Issue by s-gordon** [nimroddolev/chime_tts#71]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Calling `chime_tts.say` with tts.piper seems to pick older audio files at random for the media_player. Independent of cache being enabled or disabled. I use Hello world in the example below, but as the message changes it seems to grab historical mp3 at random.

```yaml
service: chime_tts.say
target:
  entity_id: media_player.living_room
data:
  chime_path: bright
  end_chime_path: bright
  delay: 450
  final_delay: 0
  tts_playback_speed: 100
  volume_level: 0.2
  message: Hello world
  tts_platform: tts.piper
  announce: true
```

### Describe the solution you'd like

The specified message to be played.

### Describe alternatives you've considered

I have tried clearing cache; no luck there.

### Additional context

N/A
