### ISSUE TITLE
How to call from pyscript?

### ISSUE THREAD

**Issue by ILiveInAHouse** [nimroddolev/chime_tts#75]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I can't figure out how to call the chime_tts.say service from within pyscript.  I'm not getting any errors, but I'm also not getting any audio from the media_player.  Specifically, I don't think I'm indicating the target/entity_id properly.  Here is what I've tried:

```
    service.call("chime_tts", "say",
            data={
            'target':"media_player.entrywalltablet",
            'chime_path':"custom_chime_path_2",
            'end_chime_path':'',
            'offset':'0',
            'final_delay':'0',
            'tts_playback_speed':'100',
            'volume_level':'1',
            'message':"Not Ready",
            'tts_platform':"google_translate",
            'gender':"female",
            'announce':'true'})

```

This is the yaml in Developer->Services that does work (produces audio):

```
service: chime_tts.say
target:
  entity_id: media_player.entrywalltablet
data:
  chime_path: custom_chime_path_2
  end_chime_path: ""
  offset: -300
  final_delay: 0
  tts_playback_speed: 100
  volume_level: 1
  message: hello world
  tts_platform: google_translate
  gender: female
  announce: true
```

Any idea how to make the call from pyscript?

### Describe the solution you'd like

I need help with the pyscript call.

### Describe alternatives you've considered

I also tried 

    service.call("chime_tts", "say",
            data={
            'entity_id':"media_player.entrywalltablet",
            'chime_path':"custom_chime_path_2",
            'end_chime_path':'',
            'offset':'0',
            'final_delay':'0',
            'tts_playback_speed':'100',
            'volume_level':'1',
            'message':"Not Ready",
            'tts_platform':"google_translate",
            'gender':"female",
            'announce':'true'})

### Additional context

I'm not getting any related errors in the system log.
