### ISSUE TITLE
chime_tts.say service call sometimes gets stuck, requiring a restart of Home Assistant

### ISSUE THREAD

**Issue by DanDixon** [nimroddolev/chime_tts#78]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

My main notify script is occasionally getting stuck on the `chime_tts.say` call. This happened a few times with the v0.12.1-beta5, but after you released v0.13, I thought maybe it was fixed since it hasn't happened in v0.13 until today.

~~Unfortunately, I don't see any errors in the logs.~~
~~And trying to enable debug logging after the fact and calling it again, also generates nothing in the logs.~~
edit: I wasn't clicking on Show Full Logs (sorry) - when this happens again, I'll get you the logs

I've just added this to my home assistant startup scripts, so hopefully I can capture more useful info when it happens again:
```yaml
service: logger.set_level
data:
  custom_components.chime_tts: debug
```

Here's the service call I'm using that gets stuck:

```yaml
service: chime_tts.say
data:
  tts_platform: google_translate
  cache: true
  message:
    - type: chime
      path: |
        {% if (not say.startswith("-")) %} 
          {% if states['input_boolean.dog_mode'].state == 'on' %}
          media/ding-sound.mp3
          {% else %} 
          media/notify.mp3
          {% endif %}
        {% endif %}
      audio_conversion: "-filter:a volume=0.8"
    - type: tts
      message: "{{ say }}"
      delay: -800
      tld: com.au
      tts_playback_speed: 110
target:
  entity_id: media_player.minis_linked
```

### Describe the solution you'd like

My notify script (which is set to Queued) gets stuck on `chime_tts.say,` it would be great if `chime_tss.say` timed out at least.

Restarting Home Assistant fixes the problem, at least for a while.

### Describe alternatives you've considered

I could switch to the default tts script:
```yaml
service: tts.cloud_say
data:
  message: "{{ say }}"
  entity_id: media_player.minis_linked
alias: Default TTS - Backup
```

### Additional context

Thanks so much for creating this Integration. It's very powerful. I'm sorry there's another problem.

Let me know how I can help or things you'd like me to try.

**Comment by DanDixon** [comment]
I created a script to spam my notify script to say random numbers. Here's the end of the log when it gets stuck:

[chime_tts - logs - dan dixon - home-assistant_2024-02-02T00-49-28.716Z.log.txt](https://github.com/nimroddolev/chime_tts/files/14132643/chime_tts.-.logs.-.dan.dixon.-.home-assistant_2024-02-02T00-49-28.716Z.log.txt)

Looks like it starts to call it and then nothing.
I tried reloading the integration (at the end of the log) and calling it one more time.
That didn't work either.

**Comment by DanDixon** [comment]
Just figured out a way to get it stuck, but it doesn't make sense to me why this happens.

So I created a script to say random numbers:

```yaml
alias: Notify Test / Say Random Message
sequence:
  - service: script.notify_main
    data:
      say: |
        {% set random_float = (range(0, 100) | random) | int %}
        z {{ random_float }}
mode: single
icon: mdi:message
```
    
I then put that in a script that just calls it 100 times:

```yaml
alias: Notify Test / Loop Random
sequence:
  - repeat:
      count: 100
      sequence:
        - service: script.notify_test_say_random_message
          metadata: {}
          data: {}
mode: single
icon: mdi:message```

Interestingly, if I make a change to the Say Random Message while the loop is running and Save it, that will cause chime_tts to stop working until I restart Home Assistant. Otherwise, everything else seems to work just fine.

**Comment by DanDixon** [comment]
Awesome!
This seems to fix the problem with Chime TTS getting stuck and requiring a restart.
Thank you!

---

Here's a new issues I'm now seeing, and happy to post this as a new issue if that would be better.

Now, every ~20 times or so, it's fairly infrequent (it's happened 7 times now), the text converted into speech goes something like this:
"type: chime path: media/notify.mp3, audio_conversion: "-filter:a volume=0.8", message: (and then the actual message too)"

```
Logger: custom_components.chime_tts.helpers
Source: custom_components/chime_tts/helpers.py:162
Integration: Chime TTS ([documentation](https://www.github.com/nimroddolev/chime_tts/wiki), [issues](https://github.com/nimroddolev/chime_tts/issues))
First occurred: February 6, 2024 at 11:42:38 PM (7 occurrences)
Last logged: 12:45:02 PM

Message YAML parsing error at line 1, column 206: while parsing a flow mapping in "<unicode string>", line 1, column 93: ... sion': '-filter:a volume=0.8'}, {'type': 'tts', 'message': 'At t ... ^ expected ',' or '}', but got '<scalar>' in "<unicode string>", line 1, column 206: ... s out, whispers, "Goodnight, I\'ll keep the date."', 'delay': -800}] ^
```

Since posting my original message above, I've switched to using OpenAI's TTS instead of Google. Here's the latest service call:

```yaml
service: chime_tts.say
data:
  tts_platform: openai_tts
  cache: true
  message:
    - type: chime
      path: |
        {% if (not say.startswith("-")) %} 
          {% if states['input_boolean.dog_mode'].state == 'on' %}
          media/ding-sound.mp3
          {% else %} 
          media/notify.mp3
          {% endif %}
        {% endif %}
      audio_conversion: "-filter:a volume=0.8"
    - type: tts
      message: "{{ say }}"
      delay: -800
target:
  entity_id: media_player.minis_linked
enabled: true
alias: "Call a service 'Chime TTS: Say' on Minis Linked - OpenAI"
```
