### ISSUE TITLE
Feature Request: Parameter for 'Pause'/'Play' media before/after TTS announcement to improve behavior with HomePods

### ISSUE THREAD

**Issue by jonalbr** [nimroddolev/chime_tts#81]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, 
with HomePods, the `announce` parameter is currently unsupported. But what works great (at least for me) as a workaround is a small script that checks before sending the TTS media if the current state of the media_player/HomePod is “playing”. In that case, it just sends the TTS media as usually but calls `service: media_player.media_play` right after that, which resumes what was playing before.

Additionally, as I think was already mentioned in a different issue, with HomePods the volume level gets adjusted, before the current media stops. I solve this by calling `service: media_player.media_pause` before calling chime_tts. However, if I do it, it leaves a rather long period where nothing is played as chime_tts is (as expected) processing a bit before playing. If the 'pause' call were done by chime_tts after processing is complete, it would improve that behavior.

Kind regards,
Jonas

### Describe the solution you'd like

Add a parameter which, if enabled, does what I described above.

### Describe alternatives you've considered

Just continuing using an additional script with chime tts.

### Additional context

My script for reference:
```
alias: ChimeTTS Homepods
fields:
  media_player_entity:
    name: Entity ID of HomePod
    description: Provide entity of HomePod
    example: media_player.arbeitszimmer
    required: true
    selector:
      entity:
        include_entities:
          - media_player.kuche
          - media_player.schlafzimmer
          - media_player.arbeitszimmer
  message:
    name: Message
    description: The message content
    example: Das ist eine Benachrichtigung
    required: true
    selector:
      text: null
  volume_level:
    name: Volume
    description: Set volume level in percent
    example: "35"
    default: 35
    selector:
      number:
        max: 100
        min: 1
        step: 1
        mode: slider
        unit_of_measurement: "%"
sequence:
  - if:
      - condition: template
        value_template: "{{ is_state(media_player_entity, \"playing\") }}"
    then:
      - service: media_player.media_pause
        target:
          entity_id:
            - "{{ media_player_entity }}"
        data: {}
        enabled: true
      - service: chime_tts.say
        data:
          chime_path: bright
          offset: 450
          final_delay: 0
          message: "{{ message }}"
          tts_platform: edge_tts
          language: de-DE-ConradNeural
          volume_level: "{{ volume_level / 100 }}"
        target:
          entity_id: "{{ media_player_entity }}"
      - service: media_player.media_play
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
    else:
      - service: chime_tts.say
        data:
          chime_path: bright
          offset: 450
          final_delay: 0
          message: "{{ message }}"
          tts_platform: edge_tts
          language: de-DE-ConradNeural
          volume_level: "{{ volume_level / 100 }}"
        target:
          entity_id: "{{ media_player_entity }}"
mode: single
```
